### ISSUE TITLE
Expo support

### ISSUE THREAD

**Issue by cyrilmarceau** [flyskywhy/react-native-usb-serialport#6]
Hi,

Thanks for your package. 

But I have a slight problem regarding expo and this package.

When importing the RNSerialport package return null and I can't use it in.

`import { RNSerialport, definitions, actions } from "react-native-usb-serialport";`

Could you add this following code so that we can use the package from the expo module API:

build.gradle file:
```
// ...
dependencies {
  // ...
  implementation project(':expo-modules-core')
}
```

https://docs.expo.dev/modules/overview/#2-add-the--expo-modules-core--native

https://docs.expo.dev/modules/module-api/#1-set-up-the-library-as-an

Regards,

Cyril

**Comment by flyskywhy** [comment]
Is ` importing the RNSerialport package return null` only issue in expo? cause I don't meet it in bare react native.

Thanks for your description of expo module API, but I read the doc and found it's more complicated and I have no expo APP on hand to test it. Since this `react-native-usb-serialport` is stable and maybe only bug fix will need to maintain, I think you can fork it and publish as another package e.g. `expo-usb-serialport`.

**Comment by flyskywhy** [comment]
OK, good luck 😛

**Comment by cyrilmarceau** [comment]
Thanks,

We keep you informed
